import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/postcss";
import postcss from "postcss";

/**
 * Regenerates src/catalog.generated.ts — run this manually (`bun run generate:css`)
 * whenever packages/studio-catalog's component source changes. The output is checked
 * into git and imported statically by src/css.ts so that render-page.ts never needs
 * Tailwind's native oxide binary at runtime: it can't load in the CF Workers isolate
 * apps/api's workers.ts entrypoint runs in (no native Node addons there), and even
 * bundling it trips esbuild ("No loader is configured for '.node' files") long before
 * that.
 */
const catalogSourceGlob = fileURLToPath(
  new URL("../../studio-catalog/src/**/*.tsx", import.meta.url)
);
const outputPath = fileURLToPath(
  new URL("../src/catalog.generated.ts", import.meta.url)
);

const input = `@import "tailwindcss";\n@source "${catalogSourceGlob}";\n`;
const result = await postcss([tailwindcss()]).process(input, {
  from: fileURLToPath(new URL("../virtual-input.css", import.meta.url))
});

await Bun.write(
  outputPath,
  `// Generated by scripts/generate-catalog-css.ts — do not edit by hand.\n` +
    `// Regenerate with \`bun run generate:css\` after changing packages/studio-catalog.\n` +
    `export const CATALOG_CSS = ${JSON.stringify(result.css)};\n`
);

console.log(`Wrote ${outputPath}`);
